## Numpy Arrays

##### Main purpose of numpy arrays is for mathematical calculations for large amount of data

In [1]:
import numpy as np

In [2]:
a1=np.array([2,3,4,5,6])
a1

array([2, 3, 4, 5, 6])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a1.ndim

1

In [5]:
a1.shape

(5,)

In [6]:
b=[4.5,5.1,6.2]
type(b)

list

In [7]:
b1=np.array(b)
b1

array([4.5, 5.1, 6.2])

In [9]:
b1.ndim

1

In [10]:
c=[[1,2,3,4],
   [5,6,7,8]]
type(c)

list

In [12]:
c1=np.array(c)
c1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
c1.ndim

2

In [14]:
c1.shape

(2, 4)

In [15]:
d = [[[3, 4, 5, 6],
      [7, 8, 9, 10]],
      
     [[21, 22, 23, 24],
      [25, 26, 27, 28]],
     
     [[50, 51, 52, 53],
      [54, 55, 56, 57]]]
type(d)


list

In [16]:
d1=np.array(d)
d1

array([[[ 3,  4,  5,  6],
        [ 7,  8,  9, 10]],

       [[21, 22, 23, 24],
        [25, 26, 27, 28]],

       [[50, 51, 52, 53],
        [54, 55, 56, 57]]])

In [17]:
d1.ndim

3

In [18]:
np.array({"emp_id":[1,2,4]})

array({'emp_id': [1, 2, 4]}, dtype=object)

In [19]:
e=[1,"example",True,4.5]
type(e)

list

In [21]:
e1=np.array(e)
e1

array(['1', 'example', 'True', '4.5'], dtype='<U32')

In [22]:
g=[1,2,3,4,5]
type(g)

list

In [23]:
g*3

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [24]:
g*2.5

TypeError: can't multiply sequence by non-int of type 'float'

In [25]:
g1=[]
for i in g:
    g1.append(i*3)

In [26]:
g

[1, 2, 3, 4, 5]

In [27]:
g1

[3, 6, 9, 12, 15]

In [28]:
a=[4,5,6,7]
type(a)

list

In [29]:
p=1
for i in a:
    p=p*i

In [30]:
p

840

In [31]:
np.prod(a)

np.int64(840)

In [32]:
np.mean(a)

np.float64(5.5)

In [33]:
np.median(a)

np.float64(5.5)

In [34]:
np.std(a)

np.float64(1.118033988749895)

In [35]:
np.min(a)

np.int64(4)

In [36]:
b = [[3, 4, 5, 6],
     [7, 8, 9, 10],
     [23, 25, 45, 46]]

In [37]:
np.sum(b)

np.int64(191)

In [38]:
np.sum(b,axis=0)

array([33, 37, 59, 62])

In [39]:
np.sum(b,axis=1)

array([ 18,  34, 139])